version: "3.8"

services:
  nacos:
    container_name: knocknut-nacos
    image: zhusaidong/nacos-server-m1:2.0.3
    restart: always
    env_file:
      - ./docker/env/nacos-standalone-mysql.env
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: knocknut-mysql
    image: mysql:8.0.31
    ports:
      - "3306:3306"
    volumes:
      - knocknut-data:/var/lib/mysql
      - ./sql-initialization:/docker-entrypoint-initdb.d
    env_file:
      - ./docker/env/mysql.env
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  knocknut-data: