version: "3.7"

services:
  mysql:
    container_name: knocknut-mysql
    image: mysql:8.0.31
    restart: always
    ports:
      - 3306:3306
    volumes:
      - knocknut-data:/var/lib/mysql
      - ./sql-initialization:/docker-entrypoint-initdb.d
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_general_ci'
    ]
    environment:
      MYSQL_ROOT_PASSWORD: knocknut
      MYSQL_USER: devclay
      MYSQL_PASSWORD: clay@knocknut
      LANG: C.UTF-8
volumes:
  knocknut-data: