spring.flyway:
  enabled: false
server.port: 5566

spring.datasource:
  dynamic:
    primary: user
    datasource:
      user:
        lazy: true
        url: jdbc:mysql://127.0.0.1:3306/kn_user?allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8&characterEncoding=utf-8&useSSL=false
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: devclay
        password: clay@knocknut