spring:
  application.name: gateway
  profiles.active: dev

server.port: 55688

knocknut:
  auth:
    jwt:
      enabled: true
      algo: rsa
      rsa-public-key-pem: jwtAuth.key.pub
      token-type: bearer
  gateway:
    public-urls:
      - /oauth/**
      - /sso/**